#################	
#				#
#				#
#  TELEGRAM BOT	#
#	 BY VEBY	#
#  TG:@vebytop	#
#				#
#################


STICKER = ["CAACAgIAAxkBAAEJ7nFkzqdN3UAX21XXki0M3udkc-z-owACSwADWbv8JRlPW_5iiJ4WLwQ", "CAACAgIAAxkBAAEJ6jhkzBZt6am_JGL0wOd2jLxUm5rcjwACUw4AAp6wEUjRMEug2Aiz1i8E", "CAACAgIAAxkBAAEJ6eBkzBHyRzoK9gYKI5ktov2GPMteqAAC-woAAm80oUssauxdTRu1eC8E", "CAACAgIAAxkBAAEJ8FRkz-B-gnAemjQcsmJBu5WgEdC-LQACfQAD9wLIDy7JuwrdyyJJLwQ", "CAACAgIAAxkBAAEJ8FZkz-CB7GFxp3heXS31yMLbiFfP4gACFAADwDZPE61lmeS5MPY-LwQ", "CAACAgIAAxkBAAEJ8Fhkz-CF340p9RUk9H90LZM1NrcQxQACGwADwDZPE329ioPLRE1qLwQ", "CAACAgEAAxkBAAEJ8Fpkz-DN6hhFPXEQvhG8GhviYnkvEAACQwcAAr-MkATE9rvJxXyNVy8E", "CAACAgIAAxkBAAEJ8Fxkz-DP4fGTaFZHQjYFtz4jqcO3ywACdwMAAkcVaAmcBYQc8al6Xy8E", "CAACAgIAAxkBAAEJ8F5kz-DRJZV11llTBKH7LPLSRV4WzQACbgEAAmvEygpMvImkM4UgtC8E", "CAACAgIAAxkBAAEJ8GBkz-DUSOKlbwY9fqPLWzveG4q9UgAC_gMAAs9fiwcSylCe8-UtFS8E", "CAACAgIAAxkBAAEJ8GJkz-ENVwABIrKIpSwBY_MhrsF103wAAisPAALRG8FL1J3H528G6JMvBA", "CAACAgIAAxkBAAEJ8GNkz-EOY0lxNqWZNvbXkeRALdsaIQACmwYAAtJaiAHqKf6_qppkti8E", "CAACAgIAAxkBAAEJ8GVkz-EPgV1DTa8uTbgO-WJUqr6BUAACIAADkP2aFfpGPjGXOp1uLwQ", "CAACAgIAAxkBAAEJ8Ghkz-ERugExjQAB-h4eWnI7XRxUvvQAAkECAALMVEkJr2SJpUobNygvBA"]